export const phrases = [
  'Acredite na justiça, mas não a que emana dos demais e sim na tua própria.',
  'O jiu-jitsu não é sobre ser melhor do que alguém. Trata-se de ser melhor do que você era ontem.',
  'O jiu-jitsu é a arte suave que nos permite derrotar oponentes maiores e mais fortes através da técnica e da inteligência',
  'No jiu-jitsu, não há vitórias ou derrotas, apenas aprendizados.',
  'No jiu-jitsu ensina humildade, respeito e disciplina. Ele nos transforma como seres humanos além dos tatames.',
  'No jiu-jitsu, o treinamento é a chave. Quanto mais você se dedicar, mais progresso irá fazer.',
  'O jiu-jitsu não é apenas uma luta no tatame, é uma luta interna para superar seus medos e limitações.',
  'O jiu-jitsu é como a vida: às vezes você está por cima, às vezes está por baixo. A chave é nunca desistir e continuar lutando.',
  'No jiu-jitsu, a técnica supera a força. É a inteligência aplicada ao movimento que leva à vitória.',
  'O jiu-jitsu é uma arte que te desafia a sair da sua zona de conforto e enfrentar seus medos de frente.',
  'O jiu-jitsu é uma jornada infinita de autoaperfeiçoamento físico, mental e espiritual.',
  'O jiu-jitsu é uma forma de autodefesa, mas também é uma ferramenta para aprimorar o caráter e promover a paz',
  'O jiu-jitsu é uma arte que nos ensina a encontrar a calma no meio do caos.',
  'No jiu-jitsu, a persistência é mais importante do que a força. Aquele que nunca desiste é o verdadeiro vencedor.',
  'O jiu-jitsu é uma bússola que nos guia na busca constante pela excelência.',
  'O jiu-jitsu é como a água. Ele se adapta a qualquer situação e supera qualquer obstáculo.',
  'No jiu-jitsu, não há espaço para o ego. A humildade é o caminho para o progresso.',
  'O jiu-jitsu é uma arte que une mente, corpo e espírito, proporcionando equilíbrio e harmonia.',
  'O verdadeiro poder do jiu-jitsu está em usar sua mente antes de usar sua força.',
  'No jiu-jitsu, você nunca perde. Ou você ganha ou você aprende.',
  'O jiu-jitsu é uma luta de xadrez físico. Cada movimento deve ser estratégico e preciso.',
];
