import React from 'react';
import StitchesRegistry from '@/app/registry';

export const metadata = {
  title: 'Prime Jiu Jitsu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: any) {
  return (
    <html>
      <StitchesRegistry />
      <body>{children}</body>
    </html>
  );
}
